using UnityEngine;
using System.Collections;

namespace VservAdiOS
{
	/// <summary>
	/// Vserv country.
	/// </summary>
	public enum VservCountry
	{
		kVservCountry_Afghanistan ,
		kVservCountry_Albania ,
		kVservCountry_Algeria ,
		kVservCountry_AmericanSamoa ,
		kVservCountry_Andorra ,
		kVservCountry_Angola,
		kVservCountry_Anguilla,
		kVservCountry_AntiguaAndBarbuda ,
		kVservCountry_Argentina ,
		kVservCountry_Armenia ,
		kVservCountry_Aruba ,
		kVservCountry_Australia ,
		kVservCountry_Austria ,
		kVservCountry_Azerbaijan,
		kVservCountry_Bahamas ,
		kVservCountry_Bahrain ,
		kVservCountry_Bangladesh,
		kVservCountry_Barbados,
		kVservCountry_Belarun ,
		kVservCountry_Belgium ,
		kVservCountry_Belize,
		kVservCountry_Benin ,
		kVservCountry_Bermuda ,
		kVservCountry_Bhutan,
		kVservCountry_Bolivia ,
		kVservCountry_BosniaAndHerzegovina,
		kVservCountry_Botswana,
		kVservCountry_Brazil,
		kVservCountry_BruneiDarussalam,
		kVservCountry_Bulgaria,
		kVservCountry_BurkinaFaso ,
		kVservCountry_Burundi ,
		kVservCountry_Cambodia,
		kVservCountry_Cameroon,
		kVservCountry_Canada,
		kVservCountry_CapeVerde ,
		kVservCountry_CamymanIslands,
		kVservCountry_CentralAfricanRepublic,
		kVservCountry_Chad,
		kVservCountry_Chile ,
		kVservCountry_China ,
		kVservCountry_Colombia,
		kVservCountry_Comoros ,
		kVservCountry_Congo	,
		kVservCountry_CongoTheDemocraticRepublicOfCongo	,
		kVservCountry_CookIslands ,
		kVservCountry_CostaRica ,
		kVservCountry_CoteDivoire ,
		kVservCountry_Croatia ,
		kVservCountry_Cuba,
		kVservCountry_Cyprus,
		kVservCountry_CzechRepublic ,
		kVservCountry_Denmark ,
		kVservCountry_Djibouti,
		kVservCountry_Dominica,
		kVservCountry_DominicanRepublic ,
		kVservCountry_Ecuador ,
		kVservCountry_Egypt ,
		kVservCountry_ELSalvador,
		kVservCountry_EquatorialGuine ,
		kVservCountry_Eritrea ,
		kVservCountry_Estonia ,
		kVservCountry_Ethiopia,
		kVservCountry_FalklandIslandsMalvinas ,
		kVservCountry_FaroeIslands,
		kVservCountry_Fiji,
		kVservCountry_Finland ,
		kVservCountry_France,
		kVservCountry_FrenchGuiana,
		kVservCountry_FrenchPolynesia ,
		kVservCountry_Gabon ,
		kVservCountry_Gambia,
		kVservCountry_Georgia ,
		kVservCountry_Germany ,
		kVservCountry_Ghana ,
		kVservCountry_Gibraltar ,
		kVservCountry_Greece,
		kVservCountry_Greenland ,
		kVservCountry_Grenada ,
		kVservCountry_Guadeloupe,
		kVservCountry_Guam,
		kVservCountry_Guatemala ,
		kVservCountry_Guinea,
		kVservCountry_GuineaBissau,
		kVservCountry_Guyana,
		kVservCountry_Haiti ,
		kVservCountry_HolySeeVaticanCityState ,
		kVservCountry_Honduras,
		kVservCountry_Hankong ,
		kVservCountry_Hungary ,
		kVservCountry_Iceland ,
		kVservCountry_India ,
		kVservCountry_Indonesia ,
		kVservCountry_IranIslamicRepublic ,
		kVservCountry_Iraq,
		kVservCountry_Ireland ,
		kVservCountry_Israel,
		kVservCountry_Italy ,
		kVservCountry_Jamaica ,
		kVservCountry_Japan ,
		kVservCountry_Jordan,
		kVservCountry_Kazakhstan,
		kVservCountry_Kenya ,
		kVservCountry_Kiribati,
		kVservCountry_KoreaDemocraticPeoplesRepublic,
		kVservCountry_KoreaRepublic ,
		kVservCountry_Kuwait,
		kVservCountry_Kyrgyzstan,
		kVservCountry_LaoPeoplesDemocraticRepublic,
		kVservCountry_Latvia,
		kVservCountry_Lebanon ,
		kVservCountry_Lesotho ,
		kVservCountry_Liberia ,
		kVservCountry_LibyanArabJamahiriya,
		kVservCountry_Liechtenstein ,
		kVservCountry_Lithuania ,
		kVservCountry_Luxembourg,
		kVservCountry_Macedonia ,
		kVservCountry_Madagascar,
		kVservCountry_Malawi,
		kVservCountry_Malaysia,
		kVservCountry_Maldives,
		kVservCountry_Mali,
		kVservCountry_Malta ,
		kVservCountry_MarshallIslands ,
		kVservCountry_Mauritania,
		kVservCountry_Mauritius ,
		kVservCountry_Mexico,
		kVservCountry_Moldova ,
		kVservCountry_Manaco,
		kVservCountry_Mangolia,
		kVservCountry_Montengegro ,
		kVservCountry_Montserrat,
		kVservCountry_Morocco ,
		kVservCountry_Mozambique,
		kVservCountry_Myanmar ,
		kVservCountry_Namibia ,
		kVservCountry_Nauru ,
		kVservCountry_Nepal ,
		kVservCountry_Netherlands ,
		kVservCountry_NetherlandsAntilles ,
		kVservCountry_NewCaledonia,
		kVservCountry_NewZealand,
		kVservCountry_Nicargua,
		kVservCountry_Niger ,
		kVservCountry_Nigeria ,
		kVservCountry_NothernMarianaIslands ,
		kVservCountry_Norway,
		kVservCountry_Oman,
		kVservCountry_Pakistan,
		kVservCountry_Palau ,
		kVservCountry_PalestinianTeritoryOccupied ,
		kVservCountry_Panama,
		kVservCountry_PapuaNewGuinea,
		kVservCountry_paraguay,
		kVservCountry_Peru,
		kVservCountry_Philippines ,
		kVservCountry_Poland,
		kVservCountry_Portugal,
		kVservCountry_PuertoAndMiquelon ,
		kVservCountry_SaintVincentAndTheGrenadines,
		kVservCountry_Samoa ,
		kVservCountry_SanMarino ,
		kVservCountry_SaoTomeAndPrinciple ,
		kVservCountry_SaudiArabia ,
		kVservCountry_Senegal ,
		kVservCountry_Serbia,
		kVservCountry_Seychelles,
		kVservCountry_SierraLeone ,
		kVservCountry_Singapore ,
		kVservCountry_Slovakia,
		kVservCountry_Slovenia,
		kVservCountry_SolomanIslands,
		kVservCountry_Somalia ,
		kVservCountry_SouthAfrica ,
		kVservCountry_Spain ,
		kVservCountry_SriLanka,
		kVservCountry_Sudan ,
		kVservCountry_Suriname,
		kVservCountry_Swaziland ,
		kVservCountry_Sweden,
		kVservCountry_Switzerland ,
		kVservCountry_SyrianArabRepublic,
		kVservCountry_Taiwan,
		kVservCountry_Tajikistan,
		kVservCountry_TanzaniaUnitedRepublic,
		kVservCountry_Thailand,
		kVservCountry_TimorLeste,
		kVservCountry_Togo,
		kVservCountry_Tonga ,
		kVservCountry_TrinidadAndTobago ,
		kVservCountry_Tunisia ,
		kVservCountry_Turkey,
		kVservCountry_Turkmenistan,
		kVservCountry_TurksAndCalcosIslands ,
		kVservCountry_Uganda,
		kVservCountry_Ukraine ,
		kVservCountry_UnitedArabEmirates,
		kVservCountry_UnitedStates,
		kVservCountry_Uruguay ,
		kVservCountry_Uzbekistan,
		kVservCountry_Vanuatu ,
		kVservCountry_Venezuela ,
		kVservCountry_Vietnam ,
		kVservCountry_VirginislandsBritish,
		kVservCountry_VirginIslandsUS ,
		kVservCountry_WallisAndFutuna ,
		kVservCountry_Yemen ,
		kVservCountry_Zambia,
		kVservCountry_Zimbabwe
	}
}